
site:
  title: My Documentation
  url: https://sriramreddydwarampudi.github.io/second_brain/
  start_page: my-docs::index.adoc
urls:
  html_extension_style: indexify
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true