name: Deploy Antora Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator-default

      - name: Build Antora Site
        run: antora antora-playbook.yml

      - name: Set Git identity
        run: |
          git config --global user.name "sriramreddydwarampudi"
          git config --global user.email "sriramreddydwarampudi@gmail.com"

      - name: Deploy to GitHub Pages
        run: |
          cd public
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy Antora site"
          git push --force origin gh-pages