name: Deploy Antora Site

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator-default

      - name: Generate Site
        run: antora antora-playbook.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.S_S }}
          publish_dir: ./build/site  # Ensure this matches your Antora output directory